ALTER TABLE user ADD COLUMN account_status VARCHAR(255) NOT NULL DEFAULT 'PENDING';
ALTER TABLE wallet ADD COLUMN wallet_name VARCHAR(255) NOT NULL DEFAULT 'My Wallet';    
ALTER TABLE user ADD COLUMN role VARCHAR(255) NOT NULL DEFAULT 'USER';
