services:
  # 1. Eureka Server
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  # 2. SQL Databases
  wallet-mysql:
    image: mysql:8.0
    volumes:
      - wallet-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: wallet_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234"]
      interval: 10s
      retries: 5
      start_period: 30s

  inventory-mysql:
    image: mysql:8.0
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: inventory_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234"]
      interval: 10s
      retries: 5
      start_period: 30s

  shop-mysql:
    image: mysql:8.0
    volumes:
      - shop-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop_db
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s

  # 3. Microservices
  wallet-service:
    build: ./wallet-service
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started
      wallet-mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://wallet-mysql:3306/wallet_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_started
      inventory-mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://inventory-mysql:3306/inventory_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  shop-service:
    build: ./shop-service
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_started
      shop-mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://shop-mysql:3306/shop_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
volumes:
  wallet-mysql-data:
  inventory-mysql-data:
  shop-mysql-data: